### ISSUE TITLE
Where can I find the code to further pre-train bert or roberta model?

### ISSUE THREAD

**Issue by ghost** [manueltonneau/covid-berts#1]
Thanks for releasing the models publicly. It will be helpful if you share the following details
a) Where can I find the code to further pre-train bert or roberta models?
b) Can I use hugging face transformers library to further pre-train the models? or Is there any other library ?

**Comment by manueltonneau** [comment]
Sorry for the super late response @kalyanks0611 
>Where can I find the code to further pre-train bert or roberta models?

The code to further pre-train BERT is the same as the one to pretrain BERT from scratch (just need to initialize with an existing checkpoint using the `init_checkpoint` argument) and can be found [here](https://github.com/google-research/bert/blob/master/run_pretraining.py). You can use [this code](https://github.com/google-research/bert/blob/master/create_pretraining_data.py) to create the pre-training data. [Here](https://github.com/stefan-it/turkish-bert/blob/master/CHEATSHEET.md) is one cheatsheet you can use that will help you understand the whole process. 

Hope that helps :)
